version: "3.2"
services:
  php:
    build: './php/'
    image: "phpimage:1.0"
    networks:
      - backend
    volumes:
      - ./samplephpwebsite/:/var/www/samplephpwebsite/
  apache:
    build: './apache/'
    image: "apacheimage:1.0"
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "8081:80"
    volumes:
      - ./samplephpwebsite/:/var/www/samplephpwebsite/
networks:
  frontend:
  backend: